[versions]
accompanistPermissionsVersion = "0.37.3"
agp = "8.13.1"

composeBomVersion = "2025.12.00"
constraintlayoutVersion = "2.2.1"
converterGsonVersion = "3.0.0"
datastorePreferencesVersion = "1.2.0"
firebaseAnalyticsKtxVersion = "22.5.0"
firebaseCrashlyticsKtxVersion = "19.4.4"
firebaseDatabaseKtxVersion = "21.0.0"
kotlinBom = "1.9.20"
kotlin = "2.2.21"

coreSplashscreen = "1.2.0"

glide = "5.0.5"

lifecycleViewmodelComposeVersion = "2.10.0"
okhttpVersion = "5.3.2"
playServicesAdsVersion = "24.8.0"
playServicesDriveVersion = "17.0.0"
retrofitVersion = "3.0.0"

roomRuntime = "2.8.4"
roomCompiler = "2.8.4"
roomKtx = "2.8.4"

hiltAndroidCompiler = "2.57.2"
hiltVersion = "2.57.2"
hiltNavigationVersion = "1.3.0"

appcompat = "1.7.1"

material = "1.13.0"
material3WindowSizeClass = "1.4.0"
materialIconsCore = "1.7.8"
materialIconsExtended = "1.7.8"
composeMaterial = "1.5.6"


activityComposeVersion = "1.12.1"
androidxJunit = "1.3.0"

compose = "1.0.0-beta08"

espressoCoreVersion = "3.7.0"
firebaseCrashlyticsGradle = "3.0.6"

googleServices = "4.4.4"
gradle = "8.13.1"

com-google-devtools-ksp = "2.2.20-2.0.4"
coreKtx = "1.17.0"
junit = "4.13.2"
lifecycleRuntimeKtxVersion = "2.10.0"


com-google-services = "4.4.4"
com-google-crashlytics = "3.0.6"
navigationComposeVersion = "2.9.6"
runtimeLivedataVersion = "1.10.0"
uiVersion = "1.10.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissionsVersion" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedataVersion" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "uiVersion" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferencesVersion" }
androidx-lifecycle-runtime-compose-android = { module = "androidx.lifecycle:lifecycle-runtime-compose-android", version.ref = "lifecycleViewmodelComposeVersion" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelComposeVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGsonVersion" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebaseAnalyticsKtxVersion" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebaseCrashlyticsKtxVersion" }
firebase-database-ktx = { module = "com.google.firebase:firebase-database-ktx", version.ref = "firebaseDatabaseKtxVersion" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlinBom" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }

hilt-android = { group = "com.google.dagger", name = "hilt-android" ,version.ref = "hiltVersion"}
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler" , version.ref = "hiltAndroidCompiler"}
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationVersion"}

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-window-size-class1 = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClass" }
androidx-compose-material = { module = "androidx.compose.material:material" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialIconsCore" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "composeMaterial" }


androidx-activity-compose-v193 = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }

androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }


androidx-espresso-core-v361 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-junit-v121 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-lifecycle-runtime-ktx-v287 = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }

androidx-navigation-compose-v285 = { module = "androidx.navigation:navigation-compose", version.ref = "navigationComposeVersion" }

compose = { module = "com.github.bumptech.glide:compose", version.ref = "compose" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }

google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { group = "junit", name = "junit", version.ref = "junit" }


okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAdsVersion" }
play-services-drive = { module = "com.google.android.gms:play-services-drive", version.ref = "playServicesDriveVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "com-google-devtools-ksp" }
com-google-services = { id = "com.google.gms.google-services", version.ref = "com-google-services" }
com-google-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "com-google-crashlytics" }
jetbrainsKotlinSerialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
